DROP TABLE LOG_EVENT_ALERT IF EXISTS;
CREATE TABLE LOG_EVENT_ALERT  (
    ALERT_ID_PK BIGINT IDENTITY NOT NULL PRIMARY KEY,
    EVENT_ID VARCHAR(50) UNIQUE,
    EVENT_DURATION BIGINT NOT NULL,
    EVENT_HOST VARCHAR(80) NULL,
    EVENT_TYPE VARCHAR(80) NULL,
    ALERT VARCHAR(20) NOT NULL
);

-- Assuming low hit rate of "true" value alerts, create an index for faster querying
DROP INDEX IDX_LOG_EVENT_ALERT IF EXISTS;
CREATE INDEX IDX_LOG_EVENT_ALERT ON LOG_EVENT_ALERT(ALERT);

DROP TABLE TMP_LOG_EVENT_STARTED IF EXISTS;
CREATE TABLE TMP_LOG_EVENT_STARTED  (
    ENTRY_ID_PK BIGINT IDENTITY NOT NULL PRIMARY KEY,
    EVENT_ID VARCHAR(50) UNIQUE,
    EVENT_STATE VARCHAR(20) NOT NULL,
    EVENT_TIMESTAMP BIGINT NOT NULL,
    EVENT_HOST VARCHAR(80) NULL,
    EVENT_TYPE VARCHAR(80) NULL
);

DROP TABLE TMP_LOG_EVENT_FINISHED IF EXISTS;
CREATE TABLE TMP_LOG_EVENT_FINISHED  (
    ENTRY_ID_PK BIGINT IDENTITY NOT NULL PRIMARY KEY,
    EVENT_ID VARCHAR(50) UNIQUE,
    EVENT_STATE VARCHAR(20) NOT NULL,
    EVENT_TIMESTAMP BIGINT NOT NULL,
    EVENT_HOST VARCHAR(80) NULL,
    EVENT_TYPE VARCHAR(80) NULL
);

